# Site settings
title: SigneT 60
email: secretary@sailsignet.org.uk
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://signet60.sailsignet.org.uk" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
